spending-snapshot:
	uv run adk api_server spending_snapshot_agent --allow_origins="*" --port=8081

spending-snapshot-dev:
	uv run adk web spending_snapshot_agent

chat:
	uv run adk api_server chat --allow_origins="*" --port=8082

chat-dev:
	uv run adk web chat 
